const mockPayments = [
  {
    Employee: {
      DunkinId: "1",
      DunkinBranch: "1",
      FirstName: "Steve",
      LastName: "Aoki",
      DOB: "11-30-1977",
      PhoneNumber: "310-340-7892",
    },
    Payor: {
      DunkinId: "BigRoomNeverDies",
      ABARouting: "148386123",
      AccountNumber: "12719660",
      Name: "Insomniac, LLC",
      DBA: "EDC",
      EIN: "EDC",
      Address: {
        Line1: "7000 N. Las Vegas Blvd",
        City: "Las Vegas",
        State: "NV",
        Zip: "89115",
      },
    },
    Payee: {
      PlaidId: "1111",
      LoanAccountNumber: "1111",
    },
    Amount: 50000,
    status: "pending",
    methodPaymentId: "methodPaymentId1",
    batchId: "EDCLV2023",
  },
  {
    Employee: {
      DunkinId: "2",
      DunkinBranch: "2",
      FirstName: "Martin",
      LastName: "Garrix",
      DOB: "05-14-1994",
      PhoneNumber: "310-340-7892",
    },
    Payor: {
      DunkinId: "BigRoomNeverDies",
      ABARouting: "148386123",
      AccountNumber: "12719660",
      Name: "Insomniac, LLC",
      DBA: "EDC",
      EIN: "EDC",
      Address: {
        Line1: "7000 N. Las Vegas Blvd",
        City: "Las Vegas",
        State: "NV",
        Zip: "89115",
      },
    },
    Payee: {
      PlaidId: "2222",
      LoanAccountNumber: "2222",
    },
    Amount: 50000,
    status: "pending",
    methodPaymentId: "methodPaymentId2",
    batchId: "EDCLV2023",
  },
  {
    Employee: {
      DunkinId: "3",
      DunkinBranch: "3",
      FirstName: "Armin",
      LastName: "Van Buuren",
      DOB: "12-25-1976",
      PhoneNumber: "310-340-7892",
    },
    Payor: {
      DunkinId: "AStateOfTrance",
      ABARouting: "148386123",
      AccountNumber: "12719660",
      Name: "Insomniac, LLC",
      DBA: "EDC",
      EIN: "EDC",
      Address: {
        Line1: "7000 N. Las Vegas Blvd",
        City: "Las Vegas",
        State: "NV",
        Zip: "89115",
      },
    },
    Payee: {
      PlaidId: "3333",
      LoanAccountNumber: "3333",
    },
    Amount: 50000,
    status: "pending",
    methodPaymentId: "methodPaymentId3",
    batchId: "EDCLV2023",
  },
  {
    Employee: {
      DunkinId: "4",
      DunkinBranch: "4",
      FirstName: "Niles",
      LastName: "Hollowell-Dhar",
      DOB: "05-14-1994",
      PhoneNumber: "310-340-7892",
    },
    Payor: {
      DunkinId: "BigRoomNeverDies",
      ABARouting: "148386123",
      AccountNumber: "12719660",
      Name: "Insomniac, LLC",
      DBA: "EDC",
      EIN: "EDC",
      Address: {
        Line1: "7000 N. Las Vegas Blvd",
        City: "Las Vegas",
        State: "NV",
        Zip: "89115",
      },
    },
    Payee: {
      PlaidId: "4444",
      LoanAccountNumber: "4444",
    },
    Amount: 50000,
    status: "pending",
    methodPaymentId: "methodPaymentId4",
    batchId: "EDCLV2023",
  },
  {
    Employee: {
      DunkinId: "5",
      DunkinBranch: "5",
      FirstName: "Armin",
      LastName: "Van Buuren",
      DOB: "12-25-1976",
      PhoneNumber: "310-340-7892",
    },
    Payor: {
      DunkinId: "AStateOfTrance",
      ABARouting: "148386123",
      AccountNumber: "12719660",
      Name: "Insomniac, LLC",
      DBA: "EDC",
      EIN: "EDC",
      Address: {
        Line1: "7000 N. Las Vegas Blvd",
        City: "Las Vegas",
        State: "NV",
        Zip: "89115",
      },
    },
    Payee: {
      PlaidId: "3333",
      LoanAccountNumber: "3333",
    },
    Amount: 50000,
    status: "pending",
    methodPaymentId: "methodPaymentId5",
    batchId: "EDCLV2023",
  },
];

exports.mockPayments = mockPayments;
